# Generated by Django 6.0.7 on 2026-07-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('maintenance', '0002_alter_workorder_branch_alter_workorder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'غير مدفوعة'), ('paid', 'مدفوعة'), ('partial', 'مدفوعة جزئياً')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع الفرعي'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الضريبة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maintenance.workorder', verbose_name='أمر صيانة'),
        ),
    ]
