# Generated by Django 6.0.7 on 2026-07-26 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_branch_alter_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='business_hours',
            field=models.CharField(blank=True, default='الأحد - الخميس، 8:00 ص - 6:00 م', max_length=200, verbose_name='ساعات العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('general_manager', 'مدير عام'), ('branch_manager', 'مدير فرع'), ('receptionist', 'موظف استقبال'), ('technician', 'فني'), ('accountant', 'محاسب'), ('inventory_manager', 'مسؤول مخزون')], default='receptionist', max_length=30, verbose_name='الدور'),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رسالة عميل',
                'verbose_name_plural': 'رسائل العملاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
