# Generated by Django 6.0.7 on 2026-07-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_business_hours_employee_role_contactmessage'),
        ('customers', '0004_vehicle_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 نجوم'), (2, '2 نجوم'), (3, '3 نجوم'), (4, '4 نجوم'), (5, '5 نجوم')], verbose_name='التقييم')),
                ('comment', models.TextField(max_length=600, verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد للنشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_review', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'تقييم الورشة',
                'verbose_name_plural': 'تقييمات الورشة',
                'ordering': ('-created_at',),
            },
        ),
    ]
