# Generated by Django 6.0.7 on 2026-09-27 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workshopreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('window_started_at', models.DateTimeField()),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'محاولة دخول',
                'verbose_name_plural': 'محاولات الدخول',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('security', 'أمان')], max_length=20, verbose_name='الإجراء')),
                ('object_type', models.CharField(max_length=100, verbose_name='نوع السجل')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='رقم السجل')),
                ('object_repr', models.CharField(max_length=255, verbose_name='وصف السجل')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإجراء')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المنفذ')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
