# Generated by Django 6.0.7 on 2026-09-27 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loginattempt_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='appointment_capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text='أقصى عدد سيارات يمكن استقبالها في الوقت نفسه.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='سعة الموعد الواحد'),
        ),
    ]
