# Generated by Django 6.0.7 on 2026-07-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'الخدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
    ]
