# Generated by Django 6.0.7 on 2026-07-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_branch_alter_employee_user'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchstock',
            options={'verbose_name': 'مخزون الفروع', 'verbose_name_plural': 'مخزون الفروع'},
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='فرع'),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sparepart', verbose_name='القطعة'),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع'),
        ),
    ]
