# Generated by Django 6.0.7 on 2026-07-26 15:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_business_hours_employee_role_contactmessage'),
        ('inventory', '0002_alter_branchstock_options_alter_branchstock_branch_and_more'),
        ('maintenance', '0003_workorder_center_notes_workorder_scheduled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('addition', 'إضافة'), ('usage', 'استخدام في صيانة'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='sparepart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='متاحة'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى للمخزون'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='supplier',
            field=models.CharField(blank=True, max_length=150, verbose_name='المورد'),
        ),
        migrations.AddConstraint(
            model_name='branchstock',
            constraint=models.UniqueConstraint(fields=('branch', 'part'), name='unique_part_stock_per_branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.branchstock', verbose_name='المخزون'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='maintenance.workorder', verbose_name='أمر الصيانة'),
        ),
    ]
