# Generated by Django 6.0.7 on 2026-07-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, verbose_name='رقم اللوحة')),
                ('chassis_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الهيكل')),
                ('brand', models.CharField(max_length=100, verbose_name='الشركة')),
                ('model', models.CharField(max_length=100, verbose_name='الموديل')),
                ('year', models.PositiveIntegerField(verbose_name='سنة الصنع')),
                ('color', models.CharField(max_length=50, verbose_name='اللون')),
                ('mileage', models.PositiveIntegerField(verbose_name='العداد')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer')),
            ],
            options={
                'verbose_name': 'سيارة',
                'verbose_name_plural': 'السيارات',
            },
        ),
    ]
