# Generated by Django 6.0.7 on 2026-07-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
    ]
