# Generated by Django 6.0.7 on 2026-07-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('mileage', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', 'جديد'), ('inspection', 'فحص'), ('approved', 'معتمد'), ('working', 'قيد الصيانة'), ('completed', 'مكتمل'), ('delivered', 'تم التسليم')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.vehicle')),
            ],
            options={
                'verbose_name': 'أمر صيانة',
                'verbose_name_plural': 'أوامر الصيانة',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='maintenance.workorder')),
            ],
            options={
                'verbose_name': 'خدمة أمر صيانة',
                'verbose_name_plural': 'خدمات أوامر الصيانة',
            },
        ),
    ]
