# Generated by Django 6.0.7 on 2026-07-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_branch_alter_employee_user'),
        ('customers', '0002_alter_vehicle_customer'),
        ('maintenance', '0001_initial'),
        ('services', '0002_alter_service_options_alter_service_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='فرع'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='عميل'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mileage',
            field=models.PositiveIntegerField(verbose_name='العداد'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('inspection', 'فحص'), ('approved', 'معتمد'), ('working', 'قيد الصيانة'), ('completed', 'مكتمل'), ('delivered', 'تم التسليم')], default='new', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.vehicle', verbose_name='سيارة'),
        ),
        migrations.AlterField(
            model_name='workorderservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='الخدمة'),
        ),
        migrations.AlterField(
            model_name='workorderservice',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='الفني'),
        ),
        migrations.AlterField(
            model_name='workorderservice',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='maintenance.workorder', verbose_name='أمر صيانة'),
        ),
    ]
