# Generated by Django 6.0.7 on 2026-07-26 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_branchstock_options_alter_branchstock_branch_and_more'),
        ('maintenance', '0002_alter_workorder_branch_alter_workorder_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='center_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المركز'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد الصيانة'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='maintenance.workorder')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة العرض')),
                ('notes', models.TextField(blank=True, verbose_name='تفاصيل العرض')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='حالة العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='maintenance.workorder', verbose_name='أمر الصيانة')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_orders/%Y/%m/', verbose_name='الصورة')),
                ('phase', models.CharField(choices=[('before', 'قبل الصيانة'), ('after', 'بعد الصيانة')], max_length=10, verbose_name='المرحلة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.workorder', verbose_name='أمر الصيانة')),
            ],
            options={
                'verbose_name': 'صورة صيانة',
                'verbose_name_plural': 'صور الصيانة',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.sparepart', verbose_name='قطعة الغيار')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_parts', to='maintenance.workorder', verbose_name='أمر الصيانة')),
            ],
            options={
                'verbose_name': 'قطعة مركبة',
                'verbose_name_plural': 'القطع المركبة',
            },
        ),
    ]
