# Generated by Django 6.0.7 on 2026-07-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_business_hours_employee_role_contactmessage'),
        ('customers', '0004_vehicle_is_active'),
        ('inventory', '0003_stockmovement_sparepart_is_active_and_more'),
        ('maintenance', '0003_workorder_center_notes_workorder_scheduled_at_and_more'),
        ('services', '0003_service_unique_service_name_per_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='core.employee', verbose_name='الفني المسؤول'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء العمل'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء العمل'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='فرع'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='عميل'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.vehicle', verbose_name='سيارة'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.UniqueConstraint(fields=('work_order', 'part'), name='unique_part_per_work_order'),
        ),
        migrations.AddConstraint(
            model_name='workorderservice',
            constraint=models.UniqueConstraint(fields=('work_order', 'service'), name='unique_service_per_work_order'),
        ),
    ]
