# Generated by Django 6.0.7 on 2026-07-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_business_hours_employee_role_contactmessage'),
        ('maintenance', '0004_workorder_assigned_technician_workorder_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='أنشئ بواسطة'),
        ),
    ]
