# Generated by Django 6.0.7 on 2026-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workshopreview'),
        ('customers', '0004_vehicle_is_active'),
        ('maintenance', '0005_alter_workorder_created_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('new', 'inspection', 'approved', 'working'))), fields=('vehicle',), name='one_active_work_order_per_vehicle'),
        ),
    ]
