# Generated by Django 6.0.7 on 2026-08-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workshopreview'),
        ('customers', '0004_vehicle_is_active'),
        ('maintenance', '0006_workorder_one_active_work_order_per_vehicle'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workorder',
            name='one_active_work_order_per_vehicle',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('inspection', 'بانتظار الفحص'), ('inspected', 'تم الفحص'), ('awaiting_approval', 'بانتظار موافقة العميل'), ('approved', 'معتمد'), ('working', 'قيد الصيانة'), ('awaiting_parts', 'بانتظار قطع الغيار'), ('testing', 'قيد الاختبار'), ('ready_for_delivery', 'جاهز للتسليم'), ('completed', 'مكتمل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('new', 'inspection', 'inspected', 'awaiting_approval', 'approved', 'working', 'awaiting_parts', 'testing', 'ready_for_delivery'))), fields=('vehicle',), name='one_active_work_order_per_vehicle'),
        ),
    ]
