# Generated by Django 6.0.7 on 2026-08-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_work_order_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='expected_delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد التسليم المتوقع'),
        ),
    ]
