# Generated by Django 6.0.7 on 2026-09-27 21:02

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_workorder_delivered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderimage',
            name='image',
            field=models.ImageField(upload_to='work_orders/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), core.validators.validate_uploaded_image], verbose_name='الصورة'),
        ),
    ]
